name: Deploy Hugo

on:
  push:
    branches: [main]

jobs:
  deploy:
    environment: site - tierhive

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Check secrets
        env:
          TH_USER: ${{ secrets.TH_USER }}
          TH_KEY: ${{ secrets.TH_KEY }}
        run: |
          if [ -n "$TH_USER" ]; then
            echo "✅ TH_USER está disponible"
          else
            echo "❌ TH_USER está vacío"
            exit 1
          fi

          if [ -n "$TH_KEY" ]; then
            echo "✅ TH_KEY está disponible"
          else
            echo "❌ TH_KEY está vacío"
            exit 1
          fi

      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: us.4.pages.tierhive.com
          port: '3523'
          username: ${{ secrets.TH_USER }}
          ssh_private_key: ${{ secrets.TH_KEY }}
          local_path: ./public/*
          remote_path: /
          sftp_only: true
